pipeline {
    agent any
     parameters {
        string(defaultValue: "", description: 'What environment?', name: 'Environment')
        // choices are newline separated-- added comment
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'Maven_integration'
        jdk 'java_home'
    }
    stages {
        stage ('Checkout'){
            steps 
            {
                git (
                    url: 'http://github.com/rajashreekamat21/Rajashree.git',
                    credentialsId: 'c01e2836-e05a-48be-bbf3-a3798e54f158'
                )
            }
            
            }
    }
}
